--liquibase formatted sql
--changeset predict-app:1.0

CREATE TABLE USER_DATA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    USER_PASS VARCHAR(50) NOT NULL,
    EMAIL_ADDRESS VARCHAR(100) NOT NULL,
    CREATION_DATE DATE NOT NULL,
    LAST_MODIFICATION_DATE DATE NOT NULL
);

ALTER TABLE USER_DATA
ADD CONSTRAINT UNIQUE_USERNAME UNIQUE (USERNAME);

ALTER TABLE USER_DATA
ADD CONSTRAINT UNIQUE_EMAIL UNIQUE (EMAIL_ADDRESS);

CREATE INDEX INDEX_PK_USER_DATA_ID ON USER_DATA (ID);

